Vagrant.configure("2") do |config|
  config.berkshelf.enabled = true

  config.vm.define "knife" do |node|
    node.vm.hostname = "knife"
    node.vm.network "private_network", ip: "192.168.50.100"
    node.vm.synced_folder "..", "/chef-repo"
    node.omnibus.chef_version = :latest
    node.vm.box = "opscode-ubuntu-12.04-i386"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04-i386_provisionerless.box"
    node.vm.provider "vmware_fusion" do |v, override|
      override.vm.box = "ubuntu-12.04.3-server-amd64"
    end    
    node.vm.provision :chef_solo do |chef|
      chef.run_list = [
        "recipe[knife]"
      ]
    end
  end
end